;;; init-meow.el --- Description -*- lexical-binding: t; -*-

;;; Commentary:
;;
;; Meow modal editing configuration and keybindings
;;
;;; Code:

(use-package meow
  :ensure (:host github :repo "jidibinlin/meow")
  :demand t
  :custom-face
  (meow-normal-indicator ((t (:inherit font-lock-keyword-face :bold t))))
  (meow-motion-indicator ((t (:inherit font-lock-keyword-face :bold t))))
  (meow-keypad-indicator ((t (:inherit font-lock-keyword-face :bold t))))
  (meow-insert-indicator ((t (:inherit font-lock-keyword-face :bold t))))
  (meow-beacon-indicator ((t (:inherit font-lock-keyword-face :bold t))))
  :custom
  (meow-use-clipboard t)
  (meow-use-cursor-position-hack t)
  :config
  (defun meow-setup ()
    (setq meow-cheatsheet-layout meow-cheatsheet-layout-qwerty)
    (meow-motion-overwrite-define-key
     '("j" . meow-next)
     '("k" . meow-prev)
		 '("h" . meow-left)
		 '("l" . meow-right)
     '("<escape>" . ignore))
    (meow-normal-define-key
     '("0" . meow-expand-0)
     '("9" . meow-expand-9)
     '("8" . meow-expand-8)
     '("7" . meow-expand-7)
     '("6" . meow-expand-6)
     '("5" . meow-expand-5)
     '("4" . meow-expand-4)
     '("3" . meow-expand-3)
     '("2" . meow-expand-2)
     '("1" . meow-expand-1)
     '("-" . negative-argument)
     '(";" . meow-reverse)
     '("," . meow-inner-of-thing)
     '("." . meow-bounds-of-thing)
     '("[" . meow-beginning-of-thing)
     '("]" . meow-end-of-thing)
     '("a" . meow-append)
     '("A" . meow-open-below)
     '("b" . meow-back-word)
     '("B" . meow-back-symbol)
     '("c" . meow-change)
     '("d" . meow-delete)
     '("D" . meow-backward-delete)
     '("e" . meow-next-word)
     '("E" . meow-next-symbol)
     '("f" . meow-find)
     '("g" . meow-cancel-selection)
     '("G" . meow-grab)
     '("h" . meow-left)
     '("H" . meow-left-expand)
     '("i" . meow-insert)
     '("I" . meow-open-above)
     '("j" . meow-next)
     '("J" . meow-next-expand)
     '("k" . meow-prev)
     '("K" . meow-prev-expand)
     '("l" . meow-right)
     '("L" . meow-right-expand)
     '("m" . meow-join)
     '("n" . meow-search)
     '("o" . meow-block)
     '("O" . meow-to-block)
     '("p" . meow-yank)
     '("q" . meow-quit)
     '("Q" . meow-goto-line)
     '("r" . meow-replace)
     '("R" . meow-swap-grab)
     '("s" . meow-kill)
     '("t" . meow-till)
     '("u" . meow-undo)
     '("U" . meow-undo-in-selection)
     '("v" . meow-visit)
     '("w" . meow-mark-word)
     '("W" . meow-mark-symbol)
     '("x" . meow-line)
     '("X" . meow-goto-line)
     '("y" . meow-save)
     '("Y" . meow-sync-grab)
     '("z" . meow-pop-selection)
     '("'" . repeat)
     '("<escape>" . ignore)))
  (meow-setup)
  (meow-global-mode 1)
  (unbind-key "SPC" 'meow-normal-state-keymap)

  (defun conia/delay-jit-lock-time ()
    (setq-local jit-lock-defer-time 0.25))
  (defun conia/resume-jit-lock-time ()
    (setq-local jit-lock-defer-time 0.1))

  (add-hook 'meow-insert-enter-hook #'conia/delay-jit-lock-time)
  (add-hook 'meow-insert-exit-hook #'conia/resume-jit-lock-time)
	(add-to-list 'meow-mode-state-list '(comint-mode . insert))
	(add-to-list 'meow-mode-state-list '(eshell-mode . insert))
	(add-to-list 'meow-mode-state-list '(text-mode . insert))
	(add-to-list 'meow-mode-state-list '(org-mode . normal)))

(provide 'init-meow)
;;; init-meow.el ends here
